language: node_js
node_js:
  - '12.19'
install:
  - npm run setup

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: pages
    local_dir: examples/test-site/doc
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
  - provider: script
    script: "npm run lerna:publish"
    skip_cleanup: true
    on:
      node: "12.19"
      tags: true

defaults: &defaults
  script:
    - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - BODILESS_DOCS_COPYFILES=1 npm run build:doc
    - npm run lint
    - npm run test
    - npm run test:ci

jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME="1x-chrome Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    # - stage: test
    #  env:
    #    - STAGE_NAME="4x-electron on Travis CI"
    #  <<: *defaults
    # - stage: test
    #  env:
    #    - STAGE_NAME="4x-electron on Travis CI"
    #  <<: *defaults
    # - stage: test
    #  env:
    #    - STAGE_NAME="4x-electron on Travis CI"
    #  <<: *defaults
    # - stage: test
    #  env:
    #    - STAGE_NAME="4x-electron on Travis CI"
    #  <<: *defaults
